GET http://localhost:5116/times

###

GET http://localhost:5116/times/3

###

POST http://localhost:5116/times/
Content-Type: application/json

{
  "nome": "Real Madrid",
  "cidade": "Madrid",
  "titulosBrasileiros": 0,
  "titulosMundiais": 9
}

###

PUT http://localhost:5116/times/3
Content-Type: application/json

{
  "nome": "Barcelona",
  "cidade": "Espanha",
  "titulosBrasileiros": 0,
  "titulosMundiais": 3
}

###

DELETE http://localhost:5116/times/4