// <auto-generated />
using FutApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505191524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("FutApi.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitulosBrasileiros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitulosMundiais")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Times");
                });
#pragma warning restore 612, 618
        }
    }
}
